package com.example.cyclexbe.domain.enums;

public enum DisputeReasonCode {
    ITEM_NOT_AS_DESCRIBED,
    MISSING_DOCUMENTS,
    MECHANICAL_FAILURE,
    DELIVERY_FAILED,
    WRONG_ITEM,
    DAMAGED_DURING_DELIVERY,
    INCOMPLETE_ACCESSORIES,
    FRAUDULENT_LISTING,
    SELLER_NOT_RESPONSIVE,
    PRICE_MISMATCH,
    OTHER
}
